# Generated by Django 3.1.5 on 2021-01-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210128_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverImg',
            field=models.TextField(blank=True, default='https://i.imgur.com/BBcy6Wc.jpg', null=True),
        ),
    ]
