# Generated by Django 3.1.5 on 2021-01-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210128_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverImg',
            field=models.TextField(default='https://i.imgur.com/BBcy6Wc.jpg'),
        ),
    ]
